model_selection :
  model :
    GradientBoostingClassifier :
      search_param_grid :
        learning_rate :
          - 1
          - 0.1
          - 0.01

        n_estimmators :
          - 100
          - 200

        criterion :
          - friedman_mse

    RandomForestClassifier :
      search_param_grid :
        n_estimators:
          - 100
          - 200
          - 300
        max_depth:
          - None
          - 5
          - 10
        min_samples_split:
          - 2
          - 5
          - 10
        min_samples_leaf:
          - 1
          - 2
          - 4

    SVC :
      search_param_grid :
        C :
          - 10
          - 1
          - 0.1
        
        kernel :
          - rbf
          - linear
        
        gamma :
          - 0.1
          - 0.01
          - 0.001

    LGBMClassifier :
      search_params_grid :
        learning_rate :
          - 0.1
          - 0.01
        
        boosting_type :
          - dart
          - gbdt

        num_leaves :
          - 50
          - 20
          - 30
